language: generic
sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # this installs the google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # apply config that will modify are shell environment
  - source $HOME/google-cloud-sdk/path.bash.inc
  # this installs kubectl
  - gcloud components update kubectl
  # This gives us authentication to mess with the cluster
  - gcloud auth activate-service-account --key-file service-account.json
